version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/ch09"  # Leave this as "/" in your project
    schedule:
      interval: "daily"
