name: Packaging (chapter 7)

on: [push]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pipx install tox

      - name: Run black
        run: tox -e format
        working-directory: ch07/first-python-package # You don't need this in your package

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pipx install tox

      - name: Run flake8
        run: tox -e lint
        working-directory: ch07/first-python-package # You don't need this in your package

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pipx install tox

      - name: Run mypy
        run: tox -e typecheck
        working-directory: ch07/first-python-package # You don't need this in your package

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.10"
            toxenv: "py310"
          - version: "3.9"
            toxenv: "py39"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install tox
        run: pipx install tox

      - name: Run pytest
        run: tox -e ${{ matrix.python.toxenv }}
        working-directory: ch07/first-python-package # You don't need this in your package

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
